[package]
name = "regex-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
once_cell = "1.20.3"
regex = "1.11.1"


[[bin]]
name = "regx"
path = "src/main.rs"
