[package]
name = "regx-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.31", features = ["derive"] }
once_cell = "1.20.3"
regex = "1.11.1"

[[bin]]
name = "regx"
path = "src/main.rs"
